name: Bundle

on:
  push:
    branches:
      - '*'
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  bundle_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Upgrade core package
        run: yarn upgrade @data-story-org/core

      - name: Build in production environment
        run: yarn run prod

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: Bundle latest gui
          committer_name: GitHub Actions
          committer_email: actions@github.com
          # default_author: github_actions
          add: 'public --force'
