name: Bundle

on:
  push:
    branches:
      - master
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+*"]
    paths:
      - "**.ts"
      - "package*"
      - "yarn*"
      - "*.json"
      - "*.js"
      - "*rc"
      - ".github/workflows/**.yml"

jobs:
  bundle_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          useLockFile: false
          install-command: yarn --frozen-lockfile --silent

      - name: Build in production environment
        run: yarn run prod

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bundle latest gui
          file_pattern: public/ dist/ docs/
