name: Issues

on:
  push:
    branches:
      - master

jobs:
  todo:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.0.5"
        id: "todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
