name: Push

on:
  push:
    branches:
      - master
    tags-ignore: ["v[0-9]+.[0-9]+.[0-9]+*"]
    paths:
      - "**.ts"
      - "**.tsx"
      - "package*"
      - "yarn*"
      - "*.json"
      - "*.js"
      - "*.jsx"
      - "*rc"
      - ".github/workflows/**.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --silent

      - name: Format with prettier
        run: yarn format

      - name: Fix all fixable eslint warnings
        run: yarn lint:quiet:fix

      # - name: Get all unfixable eslint errors
      #   uses: wearerequired/lint-action@v1
      #   with:
      #     eslint: true
      #     eslint_extensions: js,ts
      #     neutral_check_on_warning: true

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          push_options: '--force'
          status_options: '--untracked-files=no'
          skip_dirty_check: true
