name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release_core_on_npm:
    name: 'Build and release gui'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn --silent

      - name: Bundle styles and fonts
        run: |
          mkdir lib
          yarn prod
          cp -r dist/css lib/styles
          cp -r dist/fonts lib/fonts

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: 'public'
