name: Test

on:
  push:
    branches:
      - master
    tags-ignore: ['v[0-9]+.[0-9]+.[0-9]+*']
    paths:
      - '**.ts'
      - "**.tsx"
      - 'package*'
      - 'yarn*'
      - '*.json'
      - '*.js'
      - "*.jsx"
      - '*rc'
      - '.github/workflows/**.yml'
  pull_request:
    branches:
      - '*'
    tags-ignore: ['v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  unit_tests:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn --silent

      - name: Use latest core package
        run: yarn upgrade @data-story-org/core

      - name: Test
        run: yarn test

  e2e_tests:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: 
          yarn --silent
        # env:
        #   PUPPETEER_PRODUCT: firefox

      - name: Use latest core package
        run: yarn upgrade @data-story-org/core

      - name: Build in production environment
        run: yarn run prod

      - name: Test
        run: yarn test:e2e
